baseURL: "https://mansour.blog/"
title: "Ahmed Mansour"
paginate: 15
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Ahmed Mansour"
    description: "Articles written by Ahmed Mansour. Ahmed is a programmer and an entrepreneur"
    keywords: [entrepreneurship, web development, personal finance and productivity tips, accessibility, performance, UX, Javascript]
    dateFormat: "January 2, 2006"
    defaultTheme: light # dark, auto
    showReadingTime: true
    showShareButtons: false
    showPostNavLinks: false
    showBreadCrumbs: false
    showCodeCopyButtons: true
    disableSpecial1stPost: false
    hideSummary: true
    showtoc: true
    tocopen: false
    showFullTextinRSS: true
    disableSpecial1stPost: true
    disableScrollToTop: true

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: I am Ahmed, a programmer living in Finland. This blog is home to my thoughts about things that I find interesting. Reach out at hello@mansour.blog
    socialIcons:
        - name: twitter
          url: "https://twitter.com/ahmaman_"
        - name: github
          url: "https://github.com/mansour-ahmed/"
        - name: linkedin
          url: "https://www.linkedin.com/in/ahmedmansour03/"

    editPost:
        URL: "https://github.com/mansour-ahmed/mansour.blog/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

# Search START
    # options: https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.2
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Search END

menu:
    main:
        - identifier: about
          name: About
          url: /about/
          weight: 10