[[redirects]]
  from = "/how-to-add-environment-variables-to-angular-app-on-run-time"
  to = "https://www.nordschool.com/how-to-add-environment-variables-to-angular-app-on-run-time/"

[[redirects]]
  from = "/top-angular-visual-studio-code-extensions"
  to = "https://www.nordschool.com/top-angular-visual-studio-code-extensions/"

[[redirects]]
  from = "/why-you-should-care-about-web-accessibility"
  to = "https://www.nordschool.com/why-you-should-care-about-web-accessibility/"

[[redirects]]
  from = "/2019-top-vue-visual-studio-code-extensions"
  to = "https://www.nordschool.com/2019-top-vue-visual-studio-code-extensions/"

[[redirects]]
  from = "/how-to-improve-ux-by-animated-scrolling-using-ts-js"
  to = "https://www.nordschool.com/how-to-improve-ux-by-animated-scrolling-using-ts-js/"

[[redirects]]
  from = "/jamstack-what-why-and-how"
  to = "https://www.nordschool.com/jamstack-what-why-and-how/"

[[redirects]]
  from = "/create-a-blog-with-gridsome-and-vue"
  to = "https://www.nordschool.com/create-a-blog-with-gridsome-and-vue/"

[[redirects]]
  from = "/on-being-a-pragmatic-programmer-intro"
  to = "https://www.nordschool.com/on-being-a-pragmatic-programmer-intro/"

[[redirects]]
  from = "/on-being-a-pragmatic-programmer-mentality"
  to = "https://www.nordschool.com/on-being-a-pragmatic-programmer-mentality/"

[[redirects]]
  from = "/on-being-a-pragmatic-programmer-organization-and-team"
  to = "https://www.nordschool.com/on-being-a-pragmatic-programmer-organization-and-team/"

[[redirects]]
  from = "/on-being-a-pragmatic-programmer-principles"
  to = "https://www.nordschool.com/on-being-a-pragmatic-programmer-principles/"

[[redirects]]
  from = "/enable-vs-code-debugger-for-nuxt-and-typescript"
  to = "https://www.nordschool.com/enable-vs-code-debugger-for-nuxt-and-typescript/"

[[redirects]]
  from = "/add-rss-feed-to-gridsome"
  to = "https://www.nordschool.com/add-rss-feed-to-gridsome/"

[[redirects]]
  from = "/serverless-web-application-example-architecture"
  to = "https://www.nordschool.com/serverless-web-application-example-architecture/"
